---
- template: src=celery.conf.j2 dest=/etc/supervisor/conf.d/celery.conf
  become: yes
  notify:
    - Restart Supervisor

- name: Restart Celery
  become: yes
  supervisorctl:
    name: celery
    state: restarted
