---
- name: Install RabbitMQ
  become: yes
  apt: name=rabbitmq-server state=present

- name: Set the RabbitMQ vhost
  become: yes
  rabbitmq_vhost:
    name: "{{ secrets.rabbitmq.vhost }}"
    state: present

- name: Set the RabbitMQ user
  become: yes
  rabbitmq_user:
    user: "{{ secrets.rabbitmq.user }}"
    password: "{{ secrets.rabbitmq.password }}"
    vhost: "{{ secrets.rabbitmq.vhost }}"
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
