version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.9
jobs:
  build-js:
    docker:
      - image: circleci/node:10.14.1
    steps:
      - checkout
      - restore_cache:
          key: js-cache-{{ checksum "frontend/package-lock.json" }}
      - run:
          name: Install JavaScript dependencies
          command: |
            cd frontend
            npm install
      - run:
          name: Build from webpack
          command: |
            cd frontend
            npm run build
      - save_cache:
          key: js-cache-{{ checksum "frontend/package-lock.json" }}
          paths:
            - frontend/node_modules
      - save_cache:
          key: assets-cache
          paths:
            - assets

  build-py:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: py-cache-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
      - run:
          name: Install Python dependencies
          command: |
            test -d venv || virtualenv venv
            venv/bin/pip install -r requirements.txt
            venv/bin/pip install -r requirements-dev.txt
      - save_cache:
          key: py-cache-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
          paths:
            - ~/.cache/pip
            - venv

  build-assets:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: py-cache-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
      - restore_cache:
          key: assets-cache
      - run:
          name: Run collectstatic
          command: |
            venv/bin/python3 manage.py collectstatic --noinput
      - run:
          name: Create assets tarball
          command: |
            tar czf assets-${CIRCLE_SHA1}.tar.gz -C static .
      - aws-s3/copy:
          from: "assets-*.tar.gz"
          to: "s3://collegeconductor/assets/"

  lint-py:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: py-cache-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
      - run:
          name: Lint Python code
          command: venv/bin/flake8 conductor settings manage.py
      - run:
          name: Check formatting
          command: venv/bin/black --check conductor settings manage.py
      - run:
          name: Check types
          command: 'source venv/bin/activate && make mypy'

  test-py:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: py-cache-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
      - run:
          name: Run tests
          command: venv/bin/python manage.py test

  package-py:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: py-cache-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
      - run:
          name: Package Shiv app
          command: ./package.sh
      - aws-s3/copy:
          from: "conductor-*.pyz"
          to: "s3://collegeconductor/apps/"

workflows:
  version: 2
  pipeline:
    jobs:
      - build-js
      - build-py
      - build-assets:
          requires:
            - build-js
            - build-py
      - lint-py:
          requires:
            - build-py
      - test-py:
          requires:
            - lint-py
      - package-py:
          requires:
            - test-py
