---
- name: Update apt cache
  become: yes
  apt: update_cache=yes cache_valid_time=604800

- name: Install PostgreSQL
  become: yes
  apt: name={{ item }} state=present
  with_items:
    - libpq-dev
    - postgresql
    # The Python 2 version is around for Ansible, not Django.
    - python-psycopg2
    - python3-psycopg2

- name: Create locale
  become: yes
  locale_gen: name=en_US.UTF-8 state=present

# On dev, ran:
# create database conductor encoding 'UTF8'
# lc_collate 'en_US.UTF-8' lc_ctype 'en_US.UTF-8' template template0;
- name: Create the database
  become: yes
  become_user: postgres
  postgresql_db:
    name={{ postgres.db }}
    encoding='UTF8'
    lc_collate='en_US.UTF-8'
    lc_ctype='en_US.UTF-8'
    state=present
    template='template0'

# On dev, ran:
# create role conductor password 'conductor' login nosuperuser nocreatedb;
- name: Create the database user
  become: yes
  become_user: postgres
  postgresql_user: >
    db={{ postgres.db }}
    name={{ postgres.user }}
    password={{ postgres.password }}
    role_attr_flags=NOSUPERUSER,NOCREATEDB
    state=present
