---
- name: Install Supervisor
  become: yes
  apt: name=supervisor state=present

- name: Install Nginx
  become: yes
  apt: name=nginx-core state=present
  notify:
    - Start Nginx

- name: Install uWSGI
  become: yes
  apt: name={{ item }} state=present
  with_items:
    - uwsgi
    - uwsgi-plugin-python

- name: Install Git
  become: yes
  apt: name=git state=present

- name: Install lxml compilation dependencies
  become: yes
  apt: name={{ item }} state=present
  with_items:
    - libxml2-dev
    - libxslt1-dev
    - libz-dev
    - python-dev

- name: Install Psycopg2
  become: yes
  apt: name=python-psycopg2 state=present

- name: Install Bower
  become: yes
  npm: name=bower state=present global=yes

- name: Install Python package tools
  become: yes
  apt: name={{ item }} state=present
  with_items:
    - python-pip
    - python-virtualenv

- name: Create resource account
  become: yes
  user: name=lcp createhome=no state=present

- name: Create root .ssh directory
  become: yes
  file: path=/root/.ssh owner=root group=root mode=0700 state=directory

- name: Add ssh private key
  become: yes
  copy: content="{{ ssh_private_key }}" dest=/root/.ssh/id_rsa mode="u=rw,g=,o="

- name: Create app directory
  become: yes
  file: path={{ app_path }} state=directory

- name: Fetch from GitHub
  become: yes
  git: repo=git@github.com:mblayman/lcp.git dest={{ app_path }} accept_hostkey=yes
  notify:
    - Restart application

- name: Install Python dependencies
  become: yes
  pip: >
    requirements={{ app_path }}/requirements.txt
    virtualenv={{ venv_path }}
    virtualenv_site_packages=yes
  notify:
    - Restart application

- name: Install Ember dependencies
  become: yes
  npm: path={{ ember_app_path }} state=latest

- name: Install Bower dependencies
  become: yes
  command: bower --allow-root install chdir={{ ember_app_path }}
  register: bower_result
  changed_when: "bower_result.stdout != ''"

- template: src=supervisord.conf.j2 dest=/etc/supervisor/supervisord.conf
  become: yes
  notify:
    - Restart Supervisor

- template: src=lcp.conf.j2 dest=/etc/supervisor/conf.d/lcp.conf
  become: yes
  notify:
    - Restart Supervisor

- name: Configure Nginx
  become: yes
  file: dest=/etc/nginx/sites-enabled/default state=absent

- template: src=lcp.com.j2 dest=/etc/nginx/sites-available/lcp.com
  become: yes
  notify:
    - Restart Nginx

- template: src=uwsgi_params.j2 dest=/etc/nginx/uwsgi_params
  become: yes
  notify:
    - Restart Nginx

- name: Create symlink to lcp.com
  become: yes
  file: src=/etc/nginx/sites-available/lcp.com
        dest=/etc/nginx/sites-enabled/lcp.com
        state=link
  notify:
    - Restart Nginx

- name: Create /var/www
  become: yes
  file: state=directory path=/var/www owner=root group=www-data mode=0750

- name: Create STATIC_ROOT
  become: yes
  file: state=directory path={{ django_env.STATIC_ROOT }}
        owner=www-data group=www-data mode=0750

- name: Collect static files
  become: yes
  become_user: www-data
  django_manage: command=collectstatic app_path={{ app_path }} virtualenv={{ venv_path }}
  environment: "{{ django_env }}"

- name: Migrate the database
  become: yes
  django_manage: command=migrate app_path={{ app_path }} virtualenv={{ venv_path }}
  environment: "{{ django_env }}"
