---
- name: Start Nginx
  service: name=nginx state=started

# Supervisor does not restart properly.
- name: Restart Supervisor
  sudo: yes
  #service: name=supervisor state=restarted
  shell: sudo service supervisor stop && sleep 5 && sudo service supervisor start

- name: Restart Nginx
  sudo: yes
  service: name=nginx state=restarted
