---
- name: Collect static files
  become: yes
  become_user: www-data
  django_manage: command=collectstatic app_path={{ app_path }} virtualenv={{ venv_path }}
  environment: "{{ django_env }}"

- name: Start Nginx
  service: name=nginx state=started

- name: Restart fail2ban
  become: yes
  service: name=fail2ban state=restarted

# Supervisor does not restart properly.
- name: Restart Supervisor
  become: yes
  #service: name=supervisor state=restarted
  shell: sudo service supervisor stop && sleep 5 && sudo service supervisor start

- name: Restart application
  become: yes
  supervisorctl: name=lcp state=restarted config=/etc/supervisor/supervisord.conf

- name: Restart Nginx
  become: yes
  service: name=nginx state=restarted
