---
- hosts: webservers
  roles:
    - role: kamaln7.swapfile
      swapfile_size: 2GB
      become: yes
    - role: nodesource.node
      become: yes
      nodejs_version: "9.x"
    - role: Datadog.datadog
      datadog_api_key: "{{ datadog.api_key }}"
      when: deployment == "production"
    - web
