---
- name: Install Certbot
  become: yes
  apt: name=letsencrypt state=present

- name: Install Nginx
  become: yes
  apt: name=nginx-core state=present
  notify:
    - Start Nginx

- name: Permit HTTP traffic
  become: yes
  ufw: rule=allow port=http proto=tcp

- name: Permit SSH traffic
  become: yes
  ufw: rule=allow port=ssh proto=tcp

- name: Enable the firewall
  become: yes
  ufw: state=enabled

- name: Configure Nginx
  become: yes
  file: dest=/etc/nginx/sites-enabled/default state=absent

- template: src=conductor.com.j2 dest=/etc/nginx/sites-available/conductor.com
  become: yes
  notify:
    - Restart Nginx

- template: src=uwsgi_params.j2 dest=/etc/nginx/uwsgi_params
  become: yes
  notify:
    - Restart Nginx

- name: Create symlink to conductor.com
  become: yes
  file: src=/etc/nginx/sites-available/conductor.com
        dest=/etc/nginx/sites-enabled/conductor.com
        state=link
  notify:
    - Restart Nginx

- name: Check for cert directory
  become: yes
  stat: path=/etc/letsencrypt/live/{{ root_domain }}
  register: certdir

- name: Create cert
  become: yes
  command: >
    /usr/bin/letsencrypt certonly --webroot
    --email "{{ email }}"
    --agree-tos
    --webroot-path "{{ client_root }}"
    -d "{{ root_domain }}"
    -d "{{ client_domain }}"
    -d "{{ api_domain }}"
  when: deployment == "production" and certdir.stat.isdir is not defined
  notify:
    - Restart Nginx
